--CREATE TABLE IF NOT EXISTS job_tb (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    title VARCHAR(50) NOT NULL,
--    description VARCHAR(255),
--    location VARCHAR(50) NOT NULL,
--    skills VARCHAR(255) NOT NULL,
--    company_id BIGINT NOT NULL,
--    posted_at VARCHAR(50)
--);